### ISSUE TITLE
In Day 1 you forget to add  3rd quesiton output image

### ISSUE THREAD

**Issue by ombharamadev** [dakshdua03/cei_assignments#1]
![image](https://github.com/dakshdua03/cei_assignments/assets/150242178/b4889fbc-f0e4-4b54-80cf-dfa7f83a8955)
In Day 1 you forget to add  3rd quesiton output image

**Comment by dakshdua03** [comment]
the screenshot has been added

**Comment by ombharamadev** [comment]
ok
